"""
Pulse Oximeter Worked Example - a guided validation journey, not a workflow.

A Research Journey (see shared/research_journeys.py) built around Sjoding
et al. (2020, NEJM), the study behind the "Pulse oximeter racial bias"
entry in shared/case_studies.py. This page goes further than that static
case study: it lets a reader change the device's alarm threshold and
watch a fairness metric respond, using the fairness module's own
compare_post_model_bias rather than a bespoke statistic built for this
page.

Two kinds of data appear here, and the page keeps them visually and
textually separate throughout:

- Real evidence (Research Question and Real Evidence stages): the
  published occult-hypoxemia rates and cohort sizes Sjoding et al.
  actually reported. Nothing here is simulated.
- Illustrative simulation (Explore the Decision and System Consequences
  stages): a synthetic patient-level cohort generated by
  modules/fairness/core/pulse_oximeter_demo.py, calibrated to the rates
  above but not itself drawn from patient records. That module's
  docstring states exactly which parts are calibrated to the citation
  and which are a modeling assumption made for this page.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import streamlit as st

from modules.fairness.core import pulse_oximeter_demo as pod
from shared.data_handling import disclosure_for, render_data_handling_summary
from shared.journey_stages import StageTracker
from shared.report import caveat, implications, inspect_note, interpretation_note, section_header

# ---------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------

STAGE_KEY = "pulseox_stage"

STAGE_RESEARCH_QUESTION = 0
STAGE_UNDERSTAND_MEASUREMENT = 1
STAGE_REAL_EVIDENCE = 2
STAGE_EXPLORE_DECISION = 3
STAGE_SYSTEM_CONSEQUENCES = 4
STAGE_REFLECT = 5

JOURNEY_STAGES = (
    "Research question",
    "Understand measurement",
    "Real evidence",
    "Explore the decision",
    "System consequences",
    "Reflect",
)

TRACKER = StageTracker(session_key=STAGE_KEY, stage_labels=JOURNEY_STAGES)

INK_MUTED = "#898781"
GRIDLINE = "#e1e0d9"
SURFACE = "#fcfcfb"
ACCENT = "#2a78d6"
ACCENT_2 = "#c0392b"

COHORT_LABELS = {
    cohort_id: cohort.label for cohort_id, cohort in pod.PUBLISHED_COHORTS.items()
}


def _paired_measurement_svg(abg_value: int, abg_label: str) -> str:
    """
    Static diagram (not animated - see feedback on flickering icons):
    a drawn pulse-oximeter clip and a drawn blood-sample vial, taken
    minutes apart on the same patient. The device reading is fixed at
    94%; abg_value/abg_label vary with the toggle above this diagram, so
    a reader can compare the two acquisition methods on the same patient
    under both a typical and an occult-hypoxemia outcome.

    Both icons are deliberately abstract shapes (a clip, a vial), not a
    depiction of a hand or skin, since this page's subject is a
    skin-pigmentation-linked measurement error and a literal illustrated
    hand would invite exactly the kind of visual judgment this page is
    about, not illustrate the mechanism. Hover either icon (native SVG
    <title>) for detail.
    """

    abg_color = ACCENT if abg_value >= 88 else ACCENT_2

    return f"""
    <svg width="100%" height="150" viewBox="0 0 420 150" preserveAspectRatio="xMidYMid meet">
      <g style="cursor:help;">
        <title>Pulse-oximeter reading: {pod.BAND_LOWER:.0f}-{pod.BAND_UPPER:.0f}% is treated as reassuring.</title>
        <!-- finger, abstracted as a rounded capsule -->
        <rect x="75" y="18" width="32" height="58" rx="16" fill="none" stroke="{INK_MUTED}" stroke-width="1.5"/>
        <!-- sensor clip wrapped around it -->
        <rect x="62" y="34" width="58" height="24" rx="8" fill="{SURFACE}" stroke="{ACCENT}" stroke-width="2"/>
        <!-- LED indicator -->
        <circle cx="112" cy="46" r="3.5" fill="{ACCENT}"/>
        <text x="91" y="98" font-size="11" fill="{ACCENT}" text-anchor="middle">Pulse oximeter</text>
        <text x="91" y="116" font-size="15" fill="{ACCENT}" text-anchor="middle" font-weight="bold">94%</text>
        <text x="91" y="132" font-size="10" fill="{ACCENT}" text-anchor="middle">(reassuring)</text>
      </g>
      <g style="cursor:help;">
        <title>Arterial blood gas: the reference measurement, drawn separately from a blood sample.</title>
        <!-- vial -->
        <rect x="313" y="14" width="16" height="10" rx="2" fill="none" stroke="{abg_color}" stroke-width="1.5"/>
        <path d="M310 24 h22 v34 a11 11 0 0 1 -22 0 z" fill="none" stroke="{abg_color}" stroke-width="1.5"/>
        <path d="M311 42 h20 v14 a10 10 0 0 1 -20 0 z" fill="{abg_color}" fill-opacity="0.3"/>
        <text x="321" y="98" font-size="11" fill="{abg_color}" text-anchor="middle">Arterial blood gas</text>
        <text x="321" y="116" font-size="15" fill="{abg_color}" text-anchor="middle" font-weight="bold">{abg_value}%</text>
        <text x="321" y="132" font-size="10" fill="{abg_color}" text-anchor="middle">({abg_label})</text>
      </g>
      <line x1="130" y1="46" x2="300" y2="46" stroke="{GRIDLINE}" stroke-width="1.5"/>
      <text x="215" y="38" font-size="9" fill="{INK_MUTED}" text-anchor="middle">within ~10 min</text>
      <text x="215" y="10" font-size="10" fill="{INK_MUTED}" text-anchor="middle">
        Two ways of measuring the same patient's oxygen level.
      </text>
    </svg>
    """


def _light_absorption_animation_svg() -> str:
    """
    A slow, continuous loop demonstrating why pulse oximetry works at
    all: an artery's blood volume rises and falls with each heartbeat,
    so the light reaching the detector dims and brightens in step. This
    pulsatile signal (the "pulse" in pulse oximeter) is what the device
    actually measures; SpO2 comes from comparing how much red versus
    infrared light varies with that pulse.

    Deliberately not the flickering-icon kind of animation this project
    otherwise avoids: motion is smooth and continuous (opacity/radius
    eased in and out over ~1.1s, no hard cuts or strobing), and
    prefers-reduced-motion disables it entirely in favor of a static
    mid-pulse frame, since the surrounding prose already states the
    mechanism in words - the animation illustrates it, nothing here
    depends on seeing it move.
    """

    return f"""
    <style>
      @media (prefers-reduced-motion: no-preference) {{
        .pulseox-artery {{ animation: pulseox-artery-pulse 1.1s ease-in-out infinite; }}
        .pulseox-beam {{ animation: pulseox-beam-dim 1.1s ease-in-out infinite; }}
      }}
      @keyframes pulseox-artery-pulse {{
        0%, 100% {{ r: 5; opacity: 0.55; }}
        50% {{ r: 8; opacity: 0.9; }}
      }}
      @keyframes pulseox-beam-dim {{
        0%, 100% {{ opacity: 0.95; }}
        50% {{ opacity: 0.55; }}
      }}
    </style>
    <svg width="100%" height="120" viewBox="0 0 420 120" preserveAspectRatio="xMidYMid meet">
      <g style="cursor:help;">
        <title>Two LEDs (red and infrared light) shine through tissue to a detector.</title>
        <rect x="15" y="35" width="34" height="50" rx="6" fill="none" stroke="{INK_MUTED}" stroke-width="1.5"/>
        <circle cx="32" cy="52" r="4" fill="{ACCENT_2}"/>
        <circle cx="32" cy="68" r="4" fill="#7a2020"/>
        <text x="32" y="100" font-size="9" fill="{INK_MUTED}" text-anchor="middle">Red + infrared LEDs</text>
      </g>
      <rect class="pulseox-beam" x="49" y="44" width="130" height="6" fill="{ACCENT_2}" fill-opacity="0.5"/>
      <rect class="pulseox-beam" x="49" y="60" width="130" height="6" fill="#7a2020" fill-opacity="0.5"/>
      <g style="cursor:help;">
        <title>Arterial blood volume rises and falls with each heartbeat, changing how much light passes through.</title>
        <rect x="179" y="30" width="62" height="60" rx="8" fill="none" stroke="{INK_MUTED}" stroke-width="1.5"/>
        <circle class="pulseox-artery" cx="210" cy="60" r="6" fill="{ACCENT}"/>
        <text x="210" y="105" font-size="9" fill="{INK_MUTED}" text-anchor="middle">Tissue (pulsing artery)</text>
      </g>
      <rect class="pulseox-beam" x="241" y="44" width="130" height="6" fill="{ACCENT_2}" fill-opacity="0.5"/>
      <rect class="pulseox-beam" x="241" y="60" width="130" height="6" fill="#7a2020" fill-opacity="0.5"/>
      <g style="cursor:help;">
        <title>The detector reads how much of each wavelength arrived, over and over, many times a second.</title>
        <rect x="371" y="35" width="34" height="50" rx="6" fill="none" stroke="{INK_MUTED}" stroke-width="1.5"/>
        <path d="M380 60 h6 l4 -10 l4 20 l4 -14 l4 8 h6" fill="none" stroke="{ACCENT}" stroke-width="1.5"/>
        <text x="388" y="100" font-size="9" fill="{INK_MUTED}" text-anchor="middle">Detector</text>
      </g>
    </svg>
    """


def _rate_chart_spec(cohort_id: str) -> dict:
    """
    A horizontal bar per group, x-axis explicitly labeled and expressed
    as a percentage, so the axis is self-explanatory without relying on
    a reader hovering or reading a caption elsewhere. One color for both
    bars: the axis position, not a color code, is what carries the
    group comparison here.
    """

    cohort = pod.PUBLISHED_COHORTS[cohort_id]
    rows = [
        {"Group": gr.group, "rate": gr.occult_hypoxemia_rate}
        for gr in cohort.group_rates
    ]

    return {
        "data": {"values": rows},
        "mark": {"type": "bar", "color": ACCENT},
        "encoding": {
            "y": {"field": "Group", "type": "nominal", "title": None},
            "x": {
                "field": "rate",
                "type": "quantitative",
                "title": "Occult hypoxemia rate (%)",
                "axis": {"format": ".0%"},
            },
        },
        "width": "container",
        "height": 120,
    }


# ---------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="OpenMeasure - Pulse Oximeter Case Study",
    layout="centered",
)

st.title("Pulse Oximeter Racial Bias")
st.caption(
    "A guided case study: each stage unlocks after you make a decision "
    "or inspect its consequence."
)

render_data_handling_summary(disclosure_for("pages/Pulse_Oximeter_Worked_Example.py"))

stage = TRACKER.render_breadcrumb()

TRACKER.render_restart_button()

st.divider()

# -----------------------------------------------------------------
# 0. Research question
# -----------------------------------------------------------------

section_header("Research Question")

st.markdown(
    "### Does pulse oximetry detect low blood oxygen equally well across "
    "racial groups, and what happens downstream if it does not?"
)

st.write(
    "Pulse oximeters estimate arterial oxygen saturation from light "
    "absorption through tissue, with no blood draw required."
)

st.markdown(_light_absorption_animation_svg(), unsafe_allow_html=True)
st.caption(
    "How a pulse oximeter reads oxygen level: red and infrared light "
    "pass through tissue to a detector, and an artery's blood volume "
    "rises and falls with each heartbeat, dimming and brightening the "
    "light that arrives. Comparing how much red versus infrared light "
    "varies with that pulse is what yields the SpO2 reading."
)

st.write(
    "Clinicians use the reading to triage patients and to decide how "
    "much supplemental oxygen to give. Sjoding et al. (2020) compared "
    "paired pulse-oximeter and arterial-blood-gas measurements, taken "
    "within 10 minutes of each other, across two cohorts: adult "
    "inpatients at the University of Michigan Hospital, and ICU patients "
    "across a multicenter database spanning roughly 178 hospitals from "
    "2014 to 2015."
)

st.caption(
    "This journey extends the 'Pulse oximeter racial bias' case study "
    "shown on the Measurement Validation and Fairness pages: same "
    "citation and takeaway, walked through stage by stage instead of "
    "summarized in one paragraph."
)

with st.expander("Data sources and citations"):
    st.markdown(
        """
- **Sjoding, M. W., Dickson, R. P., Iwashyna, T. J., Gay, S. E., & Valley,
  T. S. (2020).** Racial bias in pulse oximetry measurement [letter].
  *New England Journal of Medicine*, 383(25), 2477-2478.
  [doi.org/10.1056/NEJMc2029240](https://www.nejm.org/doi/full/10.1056/NEJMc2029240)
- The FDA's response to this and related findings is discussed in the
  Reflect stage below, sourced from public reporting rather than a
  bibliographic citation of the FDA's own guidance document, which this
  page has not independently reviewed.
"""
    )

if stage < STAGE_UNDERSTAND_MEASUREMENT:
    if st.button("Begin study", type="primary"):
        TRACKER.advance_to(STAGE_UNDERSTAND_MEASUREMENT)

# -----------------------------------------------------------------
# 1. Understand measurement
# -----------------------------------------------------------------

if stage >= STAGE_UNDERSTAND_MEASUREMENT:
    section_header(
        "Understand Measurement",
        "What 'occult hypoxemia' means, and why it can go undetected",
    )

    st.write(
        f"Sjoding et al. defined **occult hypoxemia** as a pulse-oximeter "
        f"reading of {pod.BAND_LOWER:.0f}-{pod.BAND_UPPER:.0f}%, treated "
        "clinically as reassuring, occurring at the same time as an "
        "arterial blood gas reading below 88%, the threshold most "
        "clinicians would act on. When this happens, the device gives no "
        "signal that anything is wrong."
    )

    acquisition_case = st.radio(
        "Two ways of measuring the same patient's oxygen level. Compare "
        "them under two outcomes:",
        options=("typical", "occult"),
        format_func=lambda key: {
            "typical": "A typical reading (both methods agree)",
            "occult": "An occult-hypoxemia case (methods disagree)",
        }[key],
        horizontal=True,
        key="pulseox_acquisition_toggle",
    )

    if acquisition_case == "typical":
        st.markdown(_paired_measurement_svg(96, "normal"), unsafe_allow_html=True)
    else:
        st.markdown(_paired_measurement_svg(82, "hypoxemic"), unsafe_allow_html=True)

    st.caption(
        "A static illustration, not a real patient record. The device "
        "reading (94%) is the same in both cases; only the reference "
        "measurement changes. Hover either icon for detail."
    )

    with st.expander("Why pulse oximeters can read differently by skin pigmentation"):
        st.write(
            "A pulse oximeter estimates oxygen saturation from how much "
            "red and infrared light tissue absorbs. Melanin also absorbs "
            "light, and is among the plausible contributors the study "
            "names for the optical measurement error it found, though the "
            "letter itself does not isolate a single mechanism."
        )

    if stage < STAGE_REAL_EVIDENCE:
        if st.button("Continue to the real evidence", type="primary"):
            TRACKER.advance_to(STAGE_REAL_EVIDENCE)

# -----------------------------------------------------------------
# 2. Real evidence
# -----------------------------------------------------------------

if stage >= STAGE_REAL_EVIDENCE:
    section_header(
        "Real Evidence",
        "Published occult-hypoxemia rates, exactly as reported",
    )

    st.caption(
        "Every number on this stage is quoted directly from Sjoding et "
        "al. (2020). Nothing here is simulated."
    )

    cohort_choice = st.radio(
        "Cohort (this choice also selects which cohort calibrates the "
        "simulation later on this page)",
        options=list(COHORT_LABELS.keys()),
        format_func=lambda key: COHORT_LABELS[key],
        horizontal=True,
        key="pulseox_cohort",
    )

    st.caption(
        "Sjoding et al. report this same disparity independently in two "
        "unrelated data sources, a single Michigan hospital and a "
        "separate multicenter ICU database. That the pattern repeats "
        "across both is part of why the finding is convincing, rather "
        "than an artifact of one hospital's patients or equipment."
    )

    published = pod.PUBLISHED_COHORTS[cohort_choice]

    st.vega_lite_chart(_rate_chart_spec(cohort_choice), theme=None, use_container_width=True)

    inspect_note(
        "The horizontal axis: the percentage of patients in this reading "
        "band whose arterial blood gas (the reference measurement) came "
        "back below 88%, despite the device reading 92-96%. It is the "
        "outcome this whole page is built around, because it is measured "
        "directly from blood, not inferred, so a longer bar means the "
        "device missed a real, clinically important low-oxygen reading "
        "more often for that group."
    )

    rate_cols = st.columns(len(published.group_rates))
    for column, group_rate in zip(rate_cols, published.group_rates):
        with column:
            st.metric(
                f"{group_rate.group} patients (n={group_rate.n})",
                f"{group_rate.occult_hypoxemia_rate * 100:.0f}%",
            )

    interpretation_note(
        f"Among patients whose device reading fell in the "
        f"{pod.BAND_LOWER:.0f}-{pod.BAND_UPPER:.0f}% band, the reported "
        "occult-hypoxemia rate is roughly three times as high for Black "
        "patients as for White patients in both cohorts."
    )

    caveat(
        "Not every Black patient in these cohorts showed occult "
        "hypoxemia. This is a difference in rate, not a rule that "
        "applies to every individual."
    )

    if stage < STAGE_EXPLORE_DECISION:
        if st.button("Continue to explore the decision", type="primary"):
            TRACKER.advance_to(STAGE_EXPLORE_DECISION)

# -----------------------------------------------------------------
# 3. Explore the decision
# -----------------------------------------------------------------

threshold: float | None = None
sim_result = None
sim_cohort_id: str | None = None

if stage >= STAGE_EXPLORE_DECISION:
    section_header(
        "Explore the Decision",
        "An adjustable alarm threshold, on a synthetic cohort",
    )

    st.warning(
        "**Illustrative simulation, not study participant data.** This "
        "stage tests a general property of decision rules, not a new "
        "empirical claim about real patients: it demonstrates the same "
        "detection-versus-false-alarm tradeoff named in the Reflect stage "
        "below (Kleinberg, Mullainathan, & Raghavan, 2017; Chouldechova, "
        "2017), applied to a population calibrated to the rates you just "
        "saw. That tradeoff is a mathematical property of any decision "
        "rule facing groups with different underlying rates, so the "
        "result holds regardless of whether the specific patients "
        "demonstrating it are real."
    )

    with st.expander("Could this be run on real patient-level data instead?"):
        st.write(
            "Yes, in principle. Sjoding et al.'s multicenter cohort draws "
            "on the eICU Collaborative Research Database, and the related "
            "MIMIC-III database covers the same era; both are hosted on "
            "PhysioNet (a public repository of research health data) "
            "under a data use agreement and a completed training course, "
            "not open download. This page does not use them directly."
        )
        st.write(
            "Both databases support questions about ICU vital-sign "
            "accuracy, staffing, and outcomes generally, not only "
            "pulse-oximetry bias; a data use agreement and IRB or "
            "not-human-subjects determination are typically expected "
            "before analysis. To run this page's threshold analysis on "
            "real records, a credentialed user would need one row per "
            "patient-measurement with three columns: SpO2 (the "
            "pulse-oximeter reading), a paired SaO2 (the arterial "
            "blood-gas reading, used to derive the true-hypoxemia label "
            "below 88%), and recorded race or ethnicity, the same "
            "three-column shape "
            "`compare_post_model_bias` in "
            "`modules/fairness/core/post_model_metrics.py` expects from "
            "any uploaded dataset on the live Fairness page, with no "
            "change to the underlying statistics."
        )

    st.caption(
        f"Simulating: **{COHORT_LABELS[cohort_choice]}** (the cohort "
        "selected above, in Real Evidence)."
    )
    sim_cohort_id = cohort_choice

    threshold = st.slider(
        "Alarm threshold: flag a patient for closer review if their "
        "pulse-oximeter reading falls below this value",
        min_value=pod.BAND_LOWER + 0.5,
        max_value=pod.BAND_UPPER - 0.5,
        value=(pod.BAND_LOWER + pod.BAND_UPPER) / 2,
        step=0.1,
        key="pulseox_threshold",
    )

    synthetic_cohort = pod.generate_synthetic_cohort(sim_cohort_id, seed=0)

    sim_result = pod.evaluate_action_threshold(
        synthetic_cohort,
        threshold,
        privileged_group="White",
        unprivileged_group="Black",
    )

    metric_cols = st.columns(2)
    with metric_cols[0]:
        st.metric(
            "Detection rate, White patients",
            f"{sim_result.privileged_true_positive_rate * 100:.0f}%",
        )
        st.metric(
            "False-alarm rate, White patients",
            f"{sim_result.privileged_false_positive_rate * 100:.0f}%",
        )
    with metric_cols[1]:
        st.metric(
            "Detection rate, Black patients",
            f"{sim_result.unprivileged_true_positive_rate * 100:.0f}%",
        )
        st.metric(
            "False-alarm rate, Black patients",
            f"{sim_result.unprivileged_false_positive_rate * 100:.0f}%",
        )

    inspect_note("How the two groups' detection rates compare at this threshold.")

    interpretation_note(
        "Equal opportunity difference (Black detection rate minus White "
        f"detection rate): {sim_result.equal_opportunity_difference * 100:+.0f} "
        "percentage points. Predictive equality difference (the same gap "
        f"for false-alarm rate): {sim_result.predictive_equality_difference * 100:+.0f} "
        "percentage points."
    )

    implications(
        "Raising the threshold catches more hypoxemic patients in both "
        "groups, but also flags more patients who were not hypoxemic. "
        "Whether raising it enough to close the detection gap comes at an "
        "acceptable false-alarm cost is a clinical judgment this page "
        "does not make for you."
    )

    st.write(
        "Wong et al. (2021), analyzing 87,971 patients across five "
        "databases, found hidden hypoxemia of this kind associated with "
        "higher mortality, later organ dysfunction, and abnormal "
        "laboratory results. Fawzy et al. (2022) found that during the "
        "COVID-19 pandemic, occult hypoxemia delayed Black and Hispanic "
        "patients' recognized eligibility for treatments reserved for "
        "patients meeting a documented oxygen-saturation threshold. Both "
        "describe the same mechanism this simulator isolates: a "
        "downstream rule that acts on the device's number inherits "
        "whatever error the device already made."
    )

    with st.expander("Data sources and citations for this stage"):
        st.markdown(
            """
- **Wong, A.-K. I., Charpignon, M.-L., Kim, H., et al. (2021).** Analysis
  of Discrepancies Between Pulse Oximetry and Arterial Oxygen Saturation
  Measurements by Race and Ethnicity and Association With Organ
  Dysfunction and Mortality. *JAMA Network Open*, 4(11), e2131674.
  [doi.org/10.1001/jamanetworkopen.2021.31674](https://doi.org/10.1001/jamanetworkopen.2021.31674)
- **Fawzy, A., Wu, T. D., Wang, K., et al. (2022).** Racial and Ethnic
  Discrepancy in Pulse Oximetry and Delayed Identification of Treatment
  Eligibility Among Patients With COVID-19. *JAMA Internal Medicine*,
  182(7), 730-738.
  [doi.org/10.1001/jamainternmed.2022.1906](https://doi.org/10.1001/jamainternmed.2022.1906)
"""
        )

    for assumption in synthetic_cohort.assumptions:
        caveat(assumption)

    if stage < STAGE_SYSTEM_CONSEQUENCES:
        if st.button("Continue to system consequences", type="primary"):
            TRACKER.advance_to(STAGE_SYSTEM_CONSEQUENCES)

# -----------------------------------------------------------------
# 4. System consequences
# -----------------------------------------------------------------

if stage >= STAGE_SYSTEM_CONSEQUENCES and sim_result is not None and threshold is not None:
    section_header(
        "System Consequences",
        "The same measurement error, carried downstream",
    )

    st.write(
        "The threshold you chose does not just change a detection rate. "
        "It changes what happens next for a patient at each step of the "
        "same care pathway."
    )

    flow_cols = st.columns(5)
    flow_steps = (
        (":material/person:", "Patient", "True oxygen level unknown to the device"),
        (
            ":material/sensors:",
            "Device reading",
            f"{pod.BAND_LOWER:.0f}-{pod.BAND_UPPER:.0f}% band, this cohort",
        ),
        (
            ":material/rule:",
            "Threshold rule",
            f"Flag if reading < {threshold:.1f}%",
        ),
        (
            ":material/emergency:",
            "Clinical action",
            (
                f"White: {sim_result.privileged_true_positive_rate * 100:.0f}% of "
                "hypoxemic patients flagged"
                f" | Black: {sim_result.unprivileged_true_positive_rate * 100:.0f}%"
            ),
        ),
        (
            ":material/monitor_heart:",
            "Oxygen decision",
            "Undetected patients receive no threshold-triggered change",
        ),
    )
    for column, (icon, label, note) in zip(flow_cols, flow_steps):
        with column:
            st.badge(label, icon=icon, color="blue")
            st.caption(note)

    implications(
        "A single downstream threshold acts on whatever the device "
        "already reported. It cannot distinguish a patient the device "
        "measured accurately from one it did not, so it cannot fully "
        "correct a gap that originates in the measurement itself."
    )

    if stage < STAGE_REFLECT:
        if st.button("Continue to reflect", type="primary"):
            TRACKER.advance_to(STAGE_REFLECT)

# -----------------------------------------------------------------
# 5. Reflect
# -----------------------------------------------------------------

if stage >= STAGE_REFLECT:
    section_header("Reflect", "What this does and does not settle")

    st.write(
        "Kleinberg, Mullainathan, & Raghavan (2017) and Chouldechova "
        "(2017) show that when an outcome's base rate differs across "
        "groups, a single decision rule generally cannot equalize both "
        "detection accuracy and false-alarm rates across those groups at "
        "once (see the 'Why one fairness metric cannot satisfy every "
        "goal' case study on the Fairness page). This page demonstrates "
        "the same tension starting one step earlier: here, the group "
        "difference originates in a measurement instrument, before any "
        "model or decision rule is applied at all."
    )

    st.write(
        "Public reporting (Healthcare Dive, December 2024, and TCTMD) "
        "describes the FDA issuing draft guidance in 2024 asking pulse "
        "oximeter manufacturers to validate accuracy across a much wider "
        "range of skin pigmentation than its 2013 guidance required. That "
        "is a regulatory system responding to a measurement problem, not "
        "a substitute for checking the instrument directly."
    )

    implications(
        "Changing a decision rule changes multiple outcomes at once, and "
        "a downstream threshold cannot necessarily eliminate a "
        "difference that originates in measurement. The lesson is not "
        "'here is the correct threshold', it is that any threshold "
        "choice should be reported alongside its effect on every group."
    )

    st.caption(
        "Back to the opening question: pulse oximetry did not detect low "
        "blood oxygen equally well across the groups Sjoding et al. "
        "studied, and no single downstream threshold fully closes that "
        "gap, because the gap originates before the threshold is applied."
    )
